[build]
  publish = "public"
  command = "yarn run netlify-build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "14.19.2"
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-ignore-optional"
